default: &default
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

# 主データベースを使います。別データベースを指定しません。
production:
  <<: *default
